name: py

on:
  push:
    branches: [source]
  pull_request:
    branches: [source]
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo pendragon content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
          python run.py
        env:
          key: ${{ secrets.key }}
          client_payload: ${{ github.event.client_payload }}
      - name: Deploy 🚀
        # if: github.ref == 'refs/heads/gh-pages'
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: .
          clean: false
